In [1]:
import torch
torch.__version__

'2.3.1+cpu'

In [ ]:
#Scalars (zero dimension tensor)
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim) #dimension

tensor(7)
0


In [5]:
#Get the python number within a tensor (for one-element tensors)
scalar.item() 

7

In [7]:
#Vectors
vector = torch.tensor([7,8])
print(vector)
print(vector.ndim)

tensor([7, 8])
1


In [9]:
#The shape of a vector tell how the elemts inside them are arranged. This has a shape of 2 (two entires) and is one dimentional
vector.shape

torch.Size([2])

In [16]:
#Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
print(matrix)
print('Dimesion:',matrix.ndim,'(because its a 2x2 matrix)')
print('Shape:',matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
Dimesion: 2 (because its a 2x2 matrix)
Shape: torch.Size([2, 2])


In [23]:
#Tensors
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(tensor)
print('Dimesion:',tensor.ndim)
print('Shape:',tensor.shape,'(1 dimension of a 3x3 matrix)')

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Dimesion: 3
Shape: torch.Size([1, 3, 3]) (1 dimension of a 3x3 matrix)


Machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers

In [26]:
#Tensor of random numbers
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.0846, 0.5276, 0.5176, 0.1685],
         [0.7727, 0.1149, 0.3130, 0.0834],
         [0.7409, 0.5332, 0.1218, 0.0974]]),
 torch.float32)

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them)

In [27]:
#Tensor of zeros
zeros = torch.zeros(size=(4,5))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.float32)

In [28]:
#Also a tensor of ones
ones = torch.ones(size=(2,3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

In [31]:
zero_to_ten = torch.arange(start=0,end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#Sometimes you might want one tensor of a certain type with the same shape as another tensor. For example, a tensor of all zeros with the same shape as a previous tensor.
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
#The default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,
                            requires_grad=False) # if True, operations performed on the tensor are recorded 
float_32_tensor,float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

In [35]:
#Tensor operations